//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are also additional information in the Exception.Data property..
        /// </summary>
        internal static string exceptionMoreInformation {
            get {
                return ResourceManager.GetString("exceptionMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is too long (more than {0} characters)..
        /// </summary>
        internal static string helperExtensionLengthLong {
            get {
                return ResourceManager.GetString("helperExtensionLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is not long enough (less than {0} characters)..
        /// </summary>
        internal static string helperExtensionLengthShort {
            get {
                return ResourceManager.GetString("helperExtensionLengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension contain non letter characters..
        /// </summary>
        internal static string helperExtensionLetter {
            get {
                return ResourceManager.GetString("helperExtensionLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension can not be null..
        /// </summary>
        internal static string helperExtensionNull {
            get {
                return ResourceManager.GetString("helperExtensionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is longer than {0} charecters. path=&apos;{1}&apos;.
        /// </summary>
        internal static string helperPathLenght {
            get {
                return ResourceManager.GetString("helperPathLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension does not exist, so it can&apos;t be loaded.
        /// </summary>
        internal static string LoadNoAllowedIO {
            get {
                return ResourceManager.GetString("LoadNoAllowedIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        internal static string methodLoadName {
            get {
                return ResourceManager.GetString("methodLoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read.
        /// </summary>
        internal static string methodReadName {
            get {
                return ResourceManager.GetString("methodReadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown in the {0} method of the {1} parser. You can find more information in the innerException property. .
        /// </summary>
        internal static string parserException {
            get {
                return ResourceManager.GetString("parserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension does not exist, so it can&apos;t be saved.
        /// </summary>
        internal static string SaveNoAllowedIO {
            get {
                return ResourceManager.GetString("SaveNoAllowedIO", resourceCulture);
            }
        }
    }
}
